# Generated by Django 4.2.2 on 2023-06-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('Id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('Precio_carrito', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('Id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
                ('Apellido', models.CharField(max_length=200)),
                ('Correo', models.CharField(max_length=200)),
                ('Contraseña', models.CharField(max_length=200)),
                ('Edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='compra',
            fields=[
                ('Id_compra', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='envio',
            fields=[
                ('Id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_postal', models.CharField(max_length=200)),
                ('Direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('Id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_P', models.CharField(max_length=200)),
                ('Presio_P', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='project',
        ),
    ]
