# Generated by Django 4.2.2 on 2023-07-03 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_carrito_cliente_compra_envio_producto_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulos',
            fields=[
                ('Id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_P', models.CharField(max_length=200)),
                ('Presio_P', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=200)),
                ('Cantidad', models.IntegerField()),
                ('img', models.CharField(default='-', max_length=2000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='compra',
        ),
        migrations.DeleteModel(
            name='envio',
        ),
        migrations.DeleteModel(
            name='producto',
        ),
        migrations.AddField(
            model_name='carrito',
            name='Id_cliente',
            field=models.ForeignKey(db_column='cliente_id_cliente', default=1000, on_delete=django.db.models.deletion.CASCADE, to='index.cliente'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='Id_producto',
            field=models.ForeignKey(db_column='Producto_id_Producto', default=1000, on_delete=django.db.models.deletion.CASCADE, to='index.articulos'),
        ),
    ]
